spring:
  application:
    name: notification-service

  # Disable Config Server completely
  cloud:
    config:
      enabled: false
  # Optional config import (quoted!)
  config:
    import: "optional:configserver:"

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
