spring:
  application:
    name: customer-service

  # Disable Config Server completely
  cloud:
    config:
      enabled: false
  # Optional config import (quoted!)
  config:
    import: "optional:configserver:"

# Datasource example (Oracle)
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##BANKING_USER
    password: BANKING_USER
    driver-class-name: oracle.jdbc.OracleDriver

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  database-platform: org.hibernate.dialect.Oracle12cDialect

# Server
server:
  port: 8081

# Eureka client
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# Logging
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

# Resilience4j (optional)
resilience4j:
  retry:
    instances:
      customerServiceRetry:
        max-attempts: 3
        wait-duration: 2s

# Swagger/OpenAPI (optional)
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
